### ISSUE TITLE
github版不支持npm link 引用

### ISSUE THREAD

**Issue by ZiBuYuCHN** [wechat-miniprogram/kbone-ui#2]
经排查，是 .vue 引入 '@utils/utils' 的锅，应该是找不到这个库。虽然webpack里面有配置，但是npm link 根本不会读webpack

**Comment by JimmyVV** [comment]
和 npm link 有啥关系？你先把文件编译出来，然后再 link 试试看。

**Comment by ZiBuYuCHN** [comment]
> 和 npm link 有啥关系？你先把文件编译出来，然后再 link 试试看。

![image](https://user-images.githubusercontent.com/36832622/71445188-9e02b300-2752-11ea-9f71-b45912169b70.png)
