### ISSUE TITLE
KCheckBoxGroup和KCheckBox联合使用事件绑定问题

### ISSUE THREAD

**Issue by yanyang1224** [wechat-miniprogram/kbone-ui#20]
<KCheckboxGroup @change="handleChange" v-model="checkboxGrpValues">
    <KCheckbox value="零度的田">零度的田</KCheckbox> 
    <KCheckbox value="小程序开发">小程序开发</KCheckbox> 
</KCheckboxGroup>

绑定的change事件没有触发，只有checkboxGrpValues值变化，如果想用kbone-ui实现全选功能请问如何实现？

**Comment by JimmyVV** [comment]
这里我跟进看看

**Comment by JimmyVV** [comment]
你是指小程序上，还是 Web 上没有触发？

**Comment by JimmyVV** [comment]
已经修复，可以尝试在 0.6.5 上运行
