### ISSUE TITLE
kbone-ui 样式问题?

### ISSUE THREAD

**Issue by xujunzhou** [wechat-miniprogram/kbone-ui#25]
https://developers.weixin.qq.com/community/minihome/doc/0004aca4cb4af86da78a2f31456400

**Comment by JimmyVV** [comment]
![image](https://user-images.githubusercontent.com/12005455/87432057-10b57c00-c61a-11ea-9a4e-2d7486b7c3a6.png)

**Comment by xujunzhou** [comment]
因为 kbone-ui 中使用了 * { margin: 0; padding: 0; } 重置样式, kbone框架底层又将*选择器转化为了class样式类, 无形中提高了* { margin: 0; padding: 0; }的权重  跟第三方框架样式会有冲突!!! 解决方式: kbone-ui的重置应该调整下.
