### ISSUE TITLE
关于KActionSheet的选项点击事件，按照文档和示例写没有任何反应

### ISSUE THREAD

**Issue by ysy-aha** [wechat-miniprogram/kbone-ui#26]
![V4RHTCJ(TSH_UBCX97@83SN](https://user-images.githubusercontent.com/32658559/86510016-e47e4c00-be1e-11ea-9847-c5c00d37e6ad.png)
![(31G0_9G0 2BLW`W1 BCQDX](https://user-images.githubusercontent.com/32658559/86510136-b4837880-be1f-11ea-856e-fc604626492b.png)
↑ 这样写点击不会有任何反应

![$RS`00H_7GF1}N}FWN Y}O0](https://user-images.githubusercontent.com/32658559/86510069-4b036a00-be1f-11ea-975d-b09efe463dac.png)
![%C0BI22A45{IU)0SV)I{KVO](https://user-images.githubusercontent.com/32658559/86510085-5eaed080-be1f-11ea-85cf-262bec5f0818.png)
↑ 这样写每次打开和关闭时都会调用 actionChose方法，且输出的value是undefined

**Comment by JimmyVV** [comment]
具体是哪一端呢？

**Comment by ysy-aha** [comment]
web，不过这个是我的kbone-ui的版本过低导致的，把版本升级到最新的就好了
