### ISSUE TITLE
使用 kbone-ui ，打小程序包，报错

### ISSUE THREAD

**Issue by saoraozhe3hao** [wechat-miniprogram/kbone-ui#3]
在 main.mp.js 中 import 'kbone-ui/lib/weui/weui.css'
npm run mp 时，报
 optimization OptimizeCssAssetsWebpackPluginTypeError: Cannot read property 'toFixed' of undefined

**Comment by JimmyVV** [comment]
这个是 kbone-cli 依赖的 css-loader 版本过低的原因，你更新一下 package.json 里面的包

```
    "css-loader": "^3.4.0",
    "cssnano": "^4.1.10",
```
