### ISSUE TITLE
KScrollView touchstart赋值错误导致手势冲突

### ISSUE THREAD

**Issue by xuxingeren** [wechat-miniprogram/kbone-ui#30]
好多天以前提了pr了，但是一直没人处理，我同时用KScrollView和其他的滚动，比如KSwiper会有冲突问题
![image](https://user-images.githubusercontent.com/22443142/88353137-ef2d6080-cd8e-11ea-8758-97686c65daa1.png)

**Comment by JimmyVV** [comment]
已经合了，会跟到后面的小版本

**Comment by JimmyVV** [comment]
最新在 0.6.13
