### ISSUE TITLE
KCell 应在不传 value 时允许使用插槽

### ISSUE THREAD

**Issue by Tidyzq** [wechat-miniprogram/kbone-ui#31]
https://github.com/wechat-miniprogram/kbone-ui/blob/fbf8bb49730cf2129311ffb472163e18e230227e/packages/KForm/KCell.vue#L3-L6

应改为
```html
<KView v-if="value || $slots.default || $scopedSlots.default" class="weui-cell__bd" > 
   <slot>{{value}}</slot>
</KView> 
```

**Comment by JuneAndGreen** [comment]
[新版本的 kbone-ui](https://wechat-miniprogram.github.io/kbone/docs/kbone-ui/#%E7%AE%80%E4%BB%8B)已支持。
